### ISSUE TITLE
Criar página inicial do sistema

### ISSUE THREAD

**Issue by Fernnandez** [Fernnandez/Riquinho#3]
Eu como **usuário cadastrado ou visitante** quero **visualizar a página inicial app Riquinho** para **obter mais informações e avaliar meu cadastro na sistema**.

 

- [ ]  Criar os cards principais #16 

- [ ]  Otimizar a reponsividade da página #17 

- [ ]  Linkar os mecanismos de login e cadastro  #18
